### ISSUE TITLE
[FEATURE] Inherit parent name in description field

### ISSUE THREAD

**Issue by eeintech** [wolflu05/inventree-bulk-plugin#5]
Example:

![image](https://user-images.githubusercontent.com/4020546/209015568-3fb41c3c-ded7-4898-a236-2b729b6e2609.png)

**Comment by wolflu05** [comment]
Hello @eeintech started to continue development on this plugin again because I have time again. This is now implemented. The syntax overall also changed. You can archive this now with `{{par.dim.1}}`. You can even access the parents parent context or the generated name, the [generate](https://github.com/wolflu05/inventree-bulk-plugin/blob/parent-in-context/README.md#generate) section on the Readme.

**Comment by eeintech** [comment]
Thanks @wolflu05 sorry I won't be using it much going forward as I have transitioned from InvenTree to other systems.
